use ASSIGNMENT
/*QUERY 13*/
SELECT P.NAME_ AS NAME, F.PLAIN_TYPE as planeType
FROM PILOT P
INNER JOIN FLIES F ON P.SSN=F.SSN
INNER JOIN PLANEsERVICE PS ON F.PLAIN_TYPE = PS.PLANE_TYPE
INNER JOIN AIRPLANE A ON A.REG#=PS.PLANErEG#
WHERE PS.DATE_ = CONVERT(date, GETDATE());