use ASSIGNMENT
/*QUERY 16*/
SELECT E.NAME_ AS NAME, PS.PLANErEG# AS PLANE_REG#, C.NAME_ AS OWNER, PS.HOURS_ AS HOURS
FROM EMPLOYEE E
INNER JOIN PLANEsERVICE PS ON E.SSN=PS.EMPsSN
INNER JOIN OWNS O ON O.AIRPLANEREG#=PS.PLANErEG#
INNER JOIN CORPORATION C ON O.CORPoWNERiD=C.ID
WHERE C.NAME_ = 'Boeing' AND O.OWNERtYPE = 'CORPORATION'
ORDER BY HOURS;