use ASSIGNMENT
/*QUERY 19*/
SELECT A.REG#, A.OF_TYPE, COUNT(PS.PLANErEG#) AS SERVICES
FROM AIRPLANE A
LEFT JOIN PLANEsERVICE PS ON PS.PLANErEG# = A.REG#
GROUP BY A.REG#, A.OF_TYPE
ORDER BY SERVICES DESC;