use ASSIGNMENT

/*QUERY 2*/
/* OWNS(CORPoWNERiD) -> CORPORATION(NAME/ADDRESS)
   OWNS(REG#/TYPE) -> AIRPLANE(OF_TYPE) -> PLANETYPE(CAPACITY) */
SELECT DISTINCT C.NAME_ AS NAME, C.ADDRESS_ AS LOCATION
FROM CORPORATION C
INNER JOIN OWNS O ON O.CORPoWNERiD = C.ID
INNER JOIN AIRPLANE A ON A.REG# = O.AIRPLANEREG# AND A.OF_TYPE = O.PLANETYPE
INNER JOIN PLANETYPE P ON P.MODEL = A.OF_TYPE
WHERE P.CAPACITY > 200;