use ASSIGNMENT
/*QUERY 21*/

SELECT OWNS.PERSONoWNERiD, COUNT(*) AS Total_Planes_Owned
FROM AIRPLANE
INNER JOIN OWNS
ON AIRPLANE.Reg# = OWNS.AIRPLANEREG#
INNER JOIN PERSON
ON OWNS.PERSONoWNERiD = PERSON.Ssn
WHERE OWNS.OWNERtYPE = 'person'
GROUP BY OWNS.PERSONoWNERiD;