use ASSIGNMENT

/*QUERY 6*/
SELECT DISTINCT O.PERSONoWNERiD AS ID, O.OWNERtYPE AS TYPE, P.NAME_ AS NAME, P.ADDRESS_ AS ADDRESS, O.PDATE
FROM OWNS O
INNER JOIN PERSON P ON O.PERSONoWNERiD = P.SSN
WHERE O.OWNERtYPE='PERSON' AND O.PDATE>=DATEADD(MONTH,-1, GETDATE())
UNION
SELECT DISTINCT O.CORPoWNERiD AS CORP_ID, O.OWNERtYPE AS TYPE, C.NAME_ AS NAME, C.ADDRESS_ AS ADDRESS, O.PDATE
FROM OWNS O
INNER JOIN CORPORATION C ON O.CORPoWNERiD = C.ID
WHERE O.OWNERtYPE='CORPORATION' AND O.PDATE>=DATEADD(MONTH,-1, GETDATE());