use ASSIGNMENT
/*QUERY 11*/
SELECT C.ID, C.NAME_ AS NAME, COUNT(*) AS PLANES
FROM CORPORATION C
INNER JOIN OWNS O ON C.ID = O.CORPoWNERiD AND O.OWNERtYPE = 'CORPORATION'
GROUP BY C.ID, C.NAME_
ORDER BY PLANES DESC;